FROM ubuntu:14.04

RUN sed -i "s/http:\/\/archive.ubuntu.com/http:\/\/mirrors.tuna.tsinghua.edu.cn/g" /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y apache2
RUN apt-get install -y php5 
RUN apt-get install -y libapache2-mod-php5
RUN rm /var/www/html/index.html

COPY src/index.php /var/www/html
COPY src/config.php /var/www/html
COPY src/run.sh /run.sh

RUN chmod +x /run.sh

EXPOSE 80

CMD ["/run.sh"]